GET http://localhost:3100/players/

###

POST http://localhost:3100/players/
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}

###

GET http://localhost:3100/players/1/

###

PUT http://localhost:3100/players/3/
Content-Type: application/json 

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}

###
DELETE http://localhost:3100/players/2/